{% set name = "qgis-plugin-manager" %}
{% set version = "1.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qgis-plugin-manager-{{ version }}.tar.gz
  sha256: 0203c46e97f31e2fe44c93c223a1bcac0a5131b201e66ed7008ea1fee4fcd572

build:
  entry_points:
    - qgis-plugin-manager = qgis_plugin_manager.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - qgis_plugin_manager
  commands:
    - pip check
    - qgis-plugin-manager --help
  requires:
    - pip

about:
  home: https://github.com/3liz/qgis-plugin-manager
  summary: Tool for downloading/managing QGIS plugins from CLI.
  dev_url: https://github.com/3liz/qgis-plugin-manager
  license: 'GPL-3.0-only'
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yuvipanda
